version: '3.3'

services:
  frontend-site:
    container_name: frontend-site
    image: '685321914474.dkr.ecr.eu-west-3.amazonaws.com/cometrica/dmc/frontend-site:{{ version }}'
    environment:
      - VIRTUAL_HOST={{ virtual_host_site }}
      - LETSENCRYPT_HOST={{ virtual_host_site }}
      - LETSENCRYPT_EMAIL={{ letsencrypt_email }}
    restart: always
    networks:
      front:
        aliases:
          - frontend-site

networks:
  front:
    external:
      name: "{{ docker_external_network_name }}"
